# See https://cloud.google.com/appengine/docs/standard/php7/config/appref for a
# complete list of `app.yaml` directives.
runtime: php73

env_variables:
    GC_PROJECT: "nolte-metrics"
    GC_BUCKET: "nolte-metrics.appspot.com"
    ALERT_EMAIL: "afenton@wearenolte.com"
